include:
  - docker-compose-db.yaml

services:
  tournament-viewer:
    build:
      context: ./tournament_viewer
      dockerfile: DockerfileDev
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:8402
        - VITE_ITGONLINE_URL=ws://online.itgeurocup.com/

    environment:
      PORT: 8401
      VITE_API_BASE_URL: http://127.0.0.1:8402
      VITE_ITGONLINE_URL: ws://online.itgeurocup.com/
    restart: always
    volumes:
        - ./tournament_viewer/src:/app/src
    ports:
      - 127.0.0.1:8401:8401
    depends_on:
      - tournament-server

  tournament-server:
    build:
      context: ./tournament_server
      dockerfile: DockerfileDev
    restart: always
    volumes:
        - ./tournament_server/src:/app/src
    ports: 
      - 127.0.0.1:8402:8402
    depends_on:
      - mariadb
    environment:
        MARIADB_DATABASE: tournament
        DATABASE_HOST: mariadb
        DATABASE_NAME: tournament
        DATABASE_USER: root
        DATABASE_PASSWORD: example
        DATABASE_PORT: 3306
        PORT: 8402
        JWT_SECRET: example_secret
        CORS_ORIGIN: http://127.0.0.1:8401,http://localhost:8401
        ITG_ONLINE_URL: ws://localhost:1337/